[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
# forge install smartcontractkit/chainlink-brownie-contracts@0.6.1 --no-commit